# Generated by Django 4.1.1 on 2022-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('cultura', models.CharField(max_length=50)),
                ('oferta_id', models.IntegerField()),
                ('oferta', models.CharField(max_length=50)),
                ('amostra_id', models.IntegerField()),
                ('produtor', models.CharField(max_length=150)),
                ('distribuidor', models.CharField(max_length=150)),
                ('rts', models.CharField(max_length=150)),
                ('ats', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Laudo',
        ),
    ]
